# Generated by Django 3.2.3 on 2021-05-31 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('todo_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('priority', models.CharField(choices=[('High', 'High'), ('medium', 'medium'), ('low', 'low')], max_length=255)),
                ('details', models.TextField(blank=True)),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todolist.status')),
            ],
        ),
    ]
